'use strict';
let me,state,tab='overview';
const $=s=>document.querySelector(s);
function node(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function button(label,handler){const n=node('button',label);n.addEventListener('click',handler);return n;}
function date(value){return value?new Date(value*1000).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})+' Gulf':'—';}
async function request(path,data){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':me?.csrf||''},body:data===undefined?undefined:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
function flash(message,error=false){const n=node('div',message,'notice '+(error?'error':'success'));$('#flash').replaceChildren(n);}
async function refresh(){try{me=await request('/api/outreach/me');state=await request('/api/outreach/state');render();}catch(e){flash(e.message,true);}}
async function action(path,data){try{await request(path,data);flash('Saved.');await refresh();}catch(e){flash(e.message,true);}}
function empty(text){return node('div',text,'empty');}
function table(headers,rows){const wrap=node('div',undefined,'tablewrap'),t=node('table'),thead=node('thead'),head=node('tr');headers.forEach(h=>head.append(node('th',h)));thead.append(head);t.append(thead);const body=node('tbody');rows.forEach(row=>{const tr=node('tr');row.forEach(value=>{const td=node('td');td.append(value instanceof Node?value:node('span',String(value??'—')));tr.append(td);});body.append(tr);});t.append(body);wrap.append(t);return wrap;}
function modal(title,fields,callback,preview){$('#modaltitle').textContent=title;$('#fields').replaceChildren();$('#modalerror').textContent='';if(preview)$('#fields').append(node('div',preview,'preview'));fields.forEach(field=>{const label=node('label',field.label);label.htmlFor='f-'+field.key;const input=document.createElement(field.type==='textarea'?'textarea':field.type==='select'?'select':'input');input.id='f-'+field.key;input.name=field.key;if(field.type==='select'){field.options.forEach(o=>{const option=node('option',o.label);option.value=o.value;input.append(option);});}else if(field.type!=='textarea')input.type=field.type||'text';if(field.value!==undefined)input.value=field.value;if(field.type!=='checkbox')input.required=field.required!==false;$('#fields').append(label,input);});$('#modalform').onsubmit=async e=>{e.preventDefault();$('#save').disabled=true;const data={};fields.forEach(field=>{const input=$('#f-'+field.key);data[field.key]=field.type==='checkbox'?input.checked:input.value;});try{await callback(data);$('#modal').close();flash('Saved.');await refresh();}catch(error){$('#modalerror').textContent=error.message;}finally{$('#save').disabled=false;}};$('#modal').showModal();}
function leadName(id){return state.leads.find(l=>l.id===id)?.company||'Lead '+id;}
function render(){const content=$('#content');content.replaceChildren();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const titles={overview:'Outreach overview',leads:'Leads & Research',drafts:'Drafts & Approval',queue:'Scheduled / Queue',sent:'Sent',inbox:'Inbox / Replies',suppression:'Bounces / Suppression',audit:'Audit activity',settings:'Domain email setup'};$('#title').textContent=titles[tab];if(tab==='overview'){const notice=node('div',state.provider_ready?'Domain email is enabled. Every send requires Senthil approval.':'Email sending is disabled. Complete domain verification and provider setup to activate the queue.','notice');content.append(notice);const stats=node('div',undefined,'stats');[['Leads',state.leads.length],['Awaiting review',state.messages.filter(m=>m.state==='draft').length],['Scheduled',state.messages.filter(m=>['queued','retry'].includes(m.state)).length],['Replies',state.inbox.length]].forEach(([label,value])=>{const n=node('div',label,'stat');n.append(node('b',String(value)));stats.append(n);});content.append(stats,node('p',state.schedule,'muted'),node('h2','Delivery analytics'));content.append(table(['State','Messages'],Object.entries(state.analytics)));content.append(node('p','A retry affects only that email. Ambiguous sends are held for reconciliation to prevent duplicates. No automatic follow-ups are sent.','muted'));}
if(tab==='leads'){content.append(button('Add lead',()=>modal('New researched prospect',[{key:'company',label:'Company'},{key:'name',label:'Contact name'},{key:'email',label:'Verified business email',type:'email'},{key:'country',label:'Country'},{key:'website',label:'Company website',type:'url'}],d=>request('/api/outreach/leads',d))));const rows=state.leads.map(lead=>{const actions=node('div',undefined,'actions');if(me.role!=='service')actions.append(button('Qualify',()=>modal('Research & qualify '+lead.company,[{key:'observation',label:'Specific observation (describe uncertain needs as a question)',type:'textarea',value:lead.observation},{key:'evidence_url',label:'Source URL',type:'url',value:lead.evidence_url},{key:'consent',label:'Consent evidence: how and when they agreed to receive contact',type:'textarea',value:lead.consent},{key:'verified',label:'I verified this business email',type:'checkbox'}],d=>request('/api/outreach/leads/'+lead.id+'/qualify',d))));if(lead.state==='qualified')actions.append(button('Research draft',()=>action('/api/outreach/leads/'+lead.id+'/draft',{})));return [lead.company,lead.email,lead.country,lead.state,actions];});content.append(rows.length?table(['Company','Contact','Country','Research state','Actions'],rows):empty('Add your first prospect, then record source research and consent.'));content.append(node('p','Research drafts use recorded source observations. They do not invent findings or use an unconfigured AI provider.','muted'));}
if(['drafts','queue','sent'].includes(tab)){const allowed={drafts:['draft','approved'],queue:['queued','retry','failed','uncertain','sending'],sent:['sent','delivered','bounced','cancelled']}[tab];if(tab==='drafts')content.append(button('Write draft',()=>draftModal()));if(tab==='queue'&&me.role==='owner')content.append(button(state.paused?'Resume queue':'Pause queue',()=>action('/api/outreach/pause',{paused:!state.paused})));const cards=node('div',undefined,'cards');state.messages.filter(m=>allowed.includes(m.state)).forEach(m=>{const card=node('article',undefined,'card'),head=node('div',undefined,'cardhead');head.append(node('h2',m.subject),node('span',m.state,'pill'));card.append(head,node('p',leadName(m.lead_id)+' · '+m.kind+' · '+(m.binding?'Commercial terms flagged':'Review required'),'muted'),node('p',m.body),node('p','Scheduled: '+date(m.scheduled)+' · Sent: '+date(m.sent_at)+' · Attempts: '+m.attempts,'muted'));if(m.error)card.append(node('div',m.error,'notice'));const actions=node('div',undefined,'actions');if(me.role==='owner'){if(m.state==='draft')actions.append(button('Review & approve',()=>modal('Senthil approval',[{key:'reviewed',label:'I checked source accuracy, recipient consent and all claims',type:'checkbox'},{key:'terms_approved',label:'I explicitly approve any pricing, scope, delivery, contract, refund or payment terms in this exact message',type:'checkbox'}],d=>request('/api/outreach/messages/'+m.id+'/approve',d),m.subject+'\n\n'+m.body)));if(m.state==='approved')actions.append(button('Schedule',()=>modal('Schedule in Gulf business hours',[{key:'when',label:'Requested date and time (your local time; shifted to next Gulf sending window)',type:'datetime-local'}],d=>request('/api/outreach/messages/'+m.id+'/schedule',{timestamp:Math.floor(new Date(d.when).getTime()/1000)}))));if(['draft','approved','queued','retry'].includes(m.state))actions.append(button('Cancel message',()=>action('/api/outreach/messages/'+m.id+'/cancel',{})));}card.append(actions);cards.append(card);});content.append(cards.childElementCount?cards:empty('No messages in this section.'));}
if(tab==='inbox'){const cards=node('div',undefined,'cards');state.inbox.forEach(mail=>{const card=node('article',undefined,'card');card.append(node('h2',mail.subject),node('p',mail.sender+' · '+date(mail.created),'muted'),node('p',mail.body));if(mail.lead_id)card.append(button('Draft reply',()=>draftModal(mail)));cards.append(card);});content.append(cards.childElementCount?cards:empty('Replies will appear here when the signed inbound webhook is connected.'));}
if(tab==='suppression'){if(me.role==='owner')content.append(button('Suppress address',()=>modal('Stop outreach to an address',[{key:'email',label:'Business email',type:'email'},{key:'reason',label:'Reason'}],d=>request('/api/outreach/suppress',d))));content.append(state.suppression.length?table(['Address','Reason','Date'],state.suppression.map(s=>[s.email,s.reason,date(s.created)])):empty('No suppressed addresses. Bounces, complaints and opt-outs block future sends.'));}
if(tab==='audit')content.append(table(['When','Actor','Action','Record'],state.audit.map(a=>[date(a.created),a.actor,a.action,a.entity])));
if(tab==='settings'){const card=node('article',undefined,'card');card.append(node('h2','Dedicated ForgeLaunch email'),node('p','Sender: '+state.sender),node('p',state.provider_ready?'Provider configured and enabled.':'Provider not yet enabled. Queue items are preserved until configuration is complete.','notice'),node('p','Configure Mailgun API and webhook signing keys on the server. Verify the chosen domain using provider-issued SPF and DKIM records. Add DMARC and the inbound MX records on a dedicated reply subdomain. Keep existing mail DNS intact.'),node('p','Events endpoint: /webhooks/mailgun/events\nInbound route: /webhooks/mailgun/inbound'),node('p',state.schedule),node('p','Only Senthil can approve and schedule messages. Admins can research and draft. The service identity can submit leads and drafts but cannot read the inbox, approve terms, schedule or send. Clients have zero outreach access.'));content.append(card);}}
function draftModal(mail){const leads=state.leads.filter(l=>l.state==='qualified'||l.state==='replied'||l.state==='contacted');if(!leads.length){flash('Qualify a lead first.',true);return;}modal(mail?'Reply draft':'New first-contact draft',[{key:'lead_id',label:'Prospect',type:'select',options:leads.map(l=>({value:l.id,label:l.company})),value:mail?.lead_id},{key:'subject',label:'Subject',value:mail?'Re: '+mail.subject:''},{key:'body',label:'Message (first contact: 180 words maximum)',type:'textarea'},{key:'binding',label:'Contains binding commercial terms',type:'checkbox'}],d=>request('/api/outreach/drafts',{...d,lead_id:Number(d.lead_id),kind:mail?'reply':'first',in_reply_to:mail?.id}));}
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.tab;render();}));$('#refresh').addEventListener('click',refresh);$('#closemodal').addEventListener('click',()=>$('#modal').close());$('#logout').addEventListener('click',async()=>{try{await request('/auth/logout',{});location.href='/admin/login';}catch(e){flash(e.message,true);}});refresh();
